// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Rates rates
//
// swagger:model Rates
type Rates struct {

	// base
	Base string `json:"base,omitempty"`

	// date
	Date string `json:"date,omitempty"`

	// rates
	Rates map[string]float64 `json:"rates,omitempty"`
}

// Validate validates this rates
func (m *Rates) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rates based on context it is used
func (m *Rates) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Rates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Rates) UnmarshalBinary(b []byte) error {
	var res Rates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
