// Code generated by go-swagger; DO NOT EDIT.

package rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLatestParams creates a new GetLatestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLatestParams() *GetLatestParams {
	return &GetLatestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLatestParamsWithTimeout creates a new GetLatestParams object
// with the ability to set a timeout on a request.
func NewGetLatestParamsWithTimeout(timeout time.Duration) *GetLatestParams {
	return &GetLatestParams{
		timeout: timeout,
	}
}

// NewGetLatestParamsWithContext creates a new GetLatestParams object
// with the ability to set a context for a request.
func NewGetLatestParamsWithContext(ctx context.Context) *GetLatestParams {
	return &GetLatestParams{
		Context: ctx,
	}
}

// NewGetLatestParamsWithHTTPClient creates a new GetLatestParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLatestParamsWithHTTPClient(client *http.Client) *GetLatestParams {
	return &GetLatestParams{
		HTTPClient: client,
	}
}

/* GetLatestParams contains all the parameters to send to the API endpoint
   for the get latest operation.

   Typically these are written to a http.Request.
*/
type GetLatestParams struct {

	/* Base.

	   The base currency

	   Default: "EUR"
	*/
	Base *string

	/* Symbols.

	   The exchange rates symbols returned
	*/
	Symbols []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get latest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLatestParams) WithDefaults() *GetLatestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get latest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLatestParams) SetDefaults() {
	var (
		baseDefault = string("EUR")
	)

	val := GetLatestParams{
		Base: &baseDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get latest params
func (o *GetLatestParams) WithTimeout(timeout time.Duration) *GetLatestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get latest params
func (o *GetLatestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get latest params
func (o *GetLatestParams) WithContext(ctx context.Context) *GetLatestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get latest params
func (o *GetLatestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get latest params
func (o *GetLatestParams) WithHTTPClient(client *http.Client) *GetLatestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get latest params
func (o *GetLatestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBase adds the base to the get latest params
func (o *GetLatestParams) WithBase(base *string) *GetLatestParams {
	o.SetBase(base)
	return o
}

// SetBase adds the base to the get latest params
func (o *GetLatestParams) SetBase(base *string) {
	o.Base = base
}

// WithSymbols adds the symbols to the get latest params
func (o *GetLatestParams) WithSymbols(symbols []string) *GetLatestParams {
	o.SetSymbols(symbols)
	return o
}

// SetSymbols adds the symbols to the get latest params
func (o *GetLatestParams) SetSymbols(symbols []string) {
	o.Symbols = symbols
}

// WriteToRequest writes these params to a swagger request
func (o *GetLatestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Base != nil {

		// query param base
		var qrBase string

		if o.Base != nil {
			qrBase = *o.Base
		}
		qBase := qrBase
		if qBase != "" {

			if err := r.SetQueryParam("base", qBase); err != nil {
				return err
			}
		}
	}

	if o.Symbols != nil {

		// binding items for symbols
		joinedSymbols := o.bindParamSymbols(reg)

		// query array param symbols
		if err := r.SetQueryParam("symbols", joinedSymbols...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetLatest binds the parameter symbols
func (o *GetLatestParams) bindParamSymbols(formats strfmt.Registry) []string {
	symbolsIR := o.Symbols

	var symbolsIC []string
	for _, symbolsIIR := range symbolsIR { // explode []string

		symbolsIIV := symbolsIIR // string as string
		symbolsIC = append(symbolsIC, symbolsIIV)
	}

	// items.CollectionFormat: "csv"
	symbolsIS := swag.JoinByFormat(symbolsIC, "csv")

	return symbolsIS
}
