// Code generated by go-swagger; DO NOT EDIT.

package rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ervitis/exchange-rates-operator/internal/models"
)

// GetByDateReader is a Reader for the GetByDate structure.
type GetByDateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetByDateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 101:
		result := NewGetByDateSwitchingProtocols()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 102:
		result := NewGetByDateProcessing()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 103:
		result := NewGetByDateCheckpoint()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 104:
		result := NewGetByDateStatus104()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 105:
		result := NewGetByDateStatus105()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 106:
		result := NewGetByDateStatus106()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 200:
		result := NewGetByDateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewGetByDateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewGetByDateAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 301:
		result := NewGetByDateMovedPermanently()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 302:
		result := NewGetByDateFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetByDateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetByDateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewGetByDateNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 502:
		result := NewGetByDateBadGateway()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewGetByDateServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 504:
		result := NewGetByDateGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 505:
		result := NewGetByDateHTTPVersionNotSupported()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetByDateSwitchingProtocols creates a GetByDateSwitchingProtocols with default headers values
func NewGetByDateSwitchingProtocols() *GetByDateSwitchingProtocols {
	return &GetByDateSwitchingProtocols{}
}

/* GetByDateSwitchingProtocols describes a response with status code 101, with default header values.

No API Key was specified or an invalid API Key was specified.
*/
type GetByDateSwitchingProtocols struct {
}

func (o *GetByDateSwitchingProtocols) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateSwitchingProtocols ", 101)
}

func (o *GetByDateSwitchingProtocols) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateProcessing creates a GetByDateProcessing with default headers values
func NewGetByDateProcessing() *GetByDateProcessing {
	return &GetByDateProcessing{}
}

/* GetByDateProcessing describes a response with status code 102, with default header values.

The account this API request is coming from is inactive.
*/
type GetByDateProcessing struct {
}

func (o *GetByDateProcessing) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateProcessing ", 102)
}

func (o *GetByDateProcessing) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateCheckpoint creates a GetByDateCheckpoint with default headers values
func NewGetByDateCheckpoint() *GetByDateCheckpoint {
	return &GetByDateCheckpoint{}
}

/* GetByDateCheckpoint describes a response with status code 103, with default header values.

The requested API endpoint does not exist.
*/
type GetByDateCheckpoint struct {
}

func (o *GetByDateCheckpoint) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateCheckpoint ", 103)
}

func (o *GetByDateCheckpoint) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateStatus104 creates a GetByDateStatus104 with default headers values
func NewGetByDateStatus104() *GetByDateStatus104 {
	return &GetByDateStatus104{}
}

/* GetByDateStatus104 describes a response with status code 104, with default header values.

The maximum allowed API amount of monthly API requests has been reached.
*/
type GetByDateStatus104 struct {
}

func (o *GetByDateStatus104) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateStatus104 ", 104)
}

func (o *GetByDateStatus104) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateStatus105 creates a GetByDateStatus105 with default headers values
func NewGetByDateStatus105() *GetByDateStatus105 {
	return &GetByDateStatus105{}
}

/* GetByDateStatus105 describes a response with status code 105, with default header values.

The current subscription plan does not support this API endpoint.
*/
type GetByDateStatus105 struct {
}

func (o *GetByDateStatus105) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateStatus105 ", 105)
}

func (o *GetByDateStatus105) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateStatus106 creates a GetByDateStatus106 with default headers values
func NewGetByDateStatus106() *GetByDateStatus106 {
	return &GetByDateStatus106{}
}

/* GetByDateStatus106 describes a response with status code 106, with default header values.

The current request did not return any results.
*/
type GetByDateStatus106 struct {
}

func (o *GetByDateStatus106) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateStatus106 ", 106)
}

func (o *GetByDateStatus106) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateOK creates a GetByDateOK with default headers values
func NewGetByDateOK() *GetByDateOK {
	return &GetByDateOK{}
}

/* GetByDateOK describes a response with status code 200, with default header values.

The foreign exchange reference rates
*/
type GetByDateOK struct {
	Payload *models.Rates
}

func (o *GetByDateOK) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateOK  %+v", 200, o.Payload)
}
func (o *GetByDateOK) GetPayload() *models.Rates {
	return o.Payload
}

func (o *GetByDateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Rates)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByDateCreated creates a GetByDateCreated with default headers values
func NewGetByDateCreated() *GetByDateCreated {
	return &GetByDateCreated{}
}

/* GetByDateCreated describes a response with status code 201, with default header values.

An invalid base currency has been entered.
*/
type GetByDateCreated struct {
}

func (o *GetByDateCreated) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateCreated ", 201)
}

func (o *GetByDateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateAccepted creates a GetByDateAccepted with default headers values
func NewGetByDateAccepted() *GetByDateAccepted {
	return &GetByDateAccepted{}
}

/* GetByDateAccepted describes a response with status code 202, with default header values.

One or more invalid symbols have been specified.
*/
type GetByDateAccepted struct {
}

func (o *GetByDateAccepted) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateAccepted ", 202)
}

func (o *GetByDateAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateMovedPermanently creates a GetByDateMovedPermanently with default headers values
func NewGetByDateMovedPermanently() *GetByDateMovedPermanently {
	return &GetByDateMovedPermanently{}
}

/* GetByDateMovedPermanently describes a response with status code 301, with default header values.

No date has been specified. [historical]
*/
type GetByDateMovedPermanently struct {
}

func (o *GetByDateMovedPermanently) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateMovedPermanently ", 301)
}

func (o *GetByDateMovedPermanently) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateFound creates a GetByDateFound with default headers values
func NewGetByDateFound() *GetByDateFound {
	return &GetByDateFound{}
}

/* GetByDateFound describes a response with status code 302, with default header values.

An invalid date has been specified. [historical, convert]
*/
type GetByDateFound struct {
}

func (o *GetByDateFound) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateFound ", 302)
}

func (o *GetByDateFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateForbidden creates a GetByDateForbidden with default headers values
func NewGetByDateForbidden() *GetByDateForbidden {
	return &GetByDateForbidden{}
}

/* GetByDateForbidden describes a response with status code 403, with default header values.

No or an invalid amount has been specified. [convert]
*/
type GetByDateForbidden struct {
}

func (o *GetByDateForbidden) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateForbidden ", 403)
}

func (o *GetByDateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateNotFound creates a GetByDateNotFound with default headers values
func NewGetByDateNotFound() *GetByDateNotFound {
	return &GetByDateNotFound{}
}

/* GetByDateNotFound describes a response with status code 404, with default header values.

The requested resource does not exist
*/
type GetByDateNotFound struct {
}

func (o *GetByDateNotFound) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateNotFound ", 404)
}

func (o *GetByDateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateNotImplemented creates a GetByDateNotImplemented with default headers values
func NewGetByDateNotImplemented() *GetByDateNotImplemented {
	return &GetByDateNotImplemented{}
}

/* GetByDateNotImplemented describes a response with status code 501, with default header values.

No or an invalid timeframe has been specified. [timeseries]
*/
type GetByDateNotImplemented struct {
}

func (o *GetByDateNotImplemented) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateNotImplemented ", 501)
}

func (o *GetByDateNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateBadGateway creates a GetByDateBadGateway with default headers values
func NewGetByDateBadGateway() *GetByDateBadGateway {
	return &GetByDateBadGateway{}
}

/* GetByDateBadGateway describes a response with status code 502, with default header values.

No or an invalid "start_date" has been specified. [timeseries, fluctuation]
*/
type GetByDateBadGateway struct {
}

func (o *GetByDateBadGateway) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateBadGateway ", 502)
}

func (o *GetByDateBadGateway) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateServiceUnavailable creates a GetByDateServiceUnavailable with default headers values
func NewGetByDateServiceUnavailable() *GetByDateServiceUnavailable {
	return &GetByDateServiceUnavailable{}
}

/* GetByDateServiceUnavailable describes a response with status code 503, with default header values.

No or an invalid "end_date" has been specified. [timeseries, fluctuation]
*/
type GetByDateServiceUnavailable struct {
}

func (o *GetByDateServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateServiceUnavailable ", 503)
}

func (o *GetByDateServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateGatewayTimeout creates a GetByDateGatewayTimeout with default headers values
func NewGetByDateGatewayTimeout() *GetByDateGatewayTimeout {
	return &GetByDateGatewayTimeout{}
}

/* GetByDateGatewayTimeout describes a response with status code 504, with default header values.

An invalid timeframe has been specified. [timeseries, fluctuation]
*/
type GetByDateGatewayTimeout struct {
}

func (o *GetByDateGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateGatewayTimeout ", 504)
}

func (o *GetByDateGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetByDateHTTPVersionNotSupported creates a GetByDateHTTPVersionNotSupported with default headers values
func NewGetByDateHTTPVersionNotSupported() *GetByDateHTTPVersionNotSupported {
	return &GetByDateHTTPVersionNotSupported{}
}

/* GetByDateHTTPVersionNotSupported describes a response with status code 505, with default header values.

The specified timeframe is too long, exceeding 365 days. [timeseries, fluctuation]
*/
type GetByDateHTTPVersionNotSupported struct {
}

func (o *GetByDateHTTPVersionNotSupported) Error() string {
	return fmt.Sprintf("[GET /{date}][%d] getByDateHttpVersionNotSupported ", 505)
}

func (o *GetByDateHTTPVersionNotSupported) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
