# permissions for end users to view exchangerateapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: exchangerateapp-viewer-role
rules:
- apiGroups:
  - app.ervitis.nazobenkyo.dev
  resources:
  - exchangerateapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.ervitis.nazobenkyo.dev
  resources:
  - exchangerateapps/status
  verbs:
  - get
