
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.ervitis.nazobenkyo.dev
  resources:
  - exchangerateapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.ervitis.nazobenkyo.dev
  resources:
  - exchangerateapps/finalizers
  verbs:
  - update
- apiGroups:
  - app.ervitis.nazobenkyo.dev
  resources:
  - exchangerateapps/status
  verbs:
  - get
  - patch
  - update
